
# Configuraciones de usuario. 
df_insumo:
  dict_cols : {
    "Mes": "Mes",
    "Vigencia": "Vigencia",
    "# ofertas": "# ofertas",
    "plu": "plu",
    "producto": "producto",
    "Marca": "Marca",
    "Sub": "Sub",
    "Venta $$ Promedio Mes": "Venta $$ Promedio Mes",
    "Promedio Mes Und": "Promedio Mes Und",
    "Precio de venta": "Precio de venta",
    "Dias de la actividad" : "Dias de la actividad"
  }
  cols_select:
    - "concat_plu_producto"
    - "plu"
    - "producto"
    - "Venta $$ Promedio Mes"
    - "Promedio Mes Und"
    - "Precio de venta"


lateral_var:
  encabezado: "Menu"

  seccion_rango_descuento:
    select_box_rng:
      clave: "selector_rango_dcto"
      etiqueta : "Seleccione un rango de descuento..."
      list_rng_dctos:
      - "5% - 10%"
      - "10% - 15%"
      - "15% - 20%"
      - "20% - 25%"
      - "25% - 30%"
      - "30% - 35%"
      - "35% - 40%"
      - "40% - 45%"
      - "45% - 50%"
    btn_confirmar_rng:
      clave : btn_confirmar_rango
      etiqueta : Confirmar rango %

  seccion_crecimiento:
    text_input_crec:
      clave: "text_input_crecimiento"
      etiqueta: "Ingrese % de crecimiento:"
      valor_por_defecto: 10
      minimo: 1
      maximo: 50
    btn_confirmar_rng:
      clave : "btn_confirmar_%_crecimiento"
      etiqueta : "Confirmar % crecimiento"

  seccion_archivo:
    file_uploader:
      clave: "archivo_excel"
      titulo: "Cargar archivo"
      uploader_msg: "📤 Adjuntar archivo Excel"
      limit_msg: "Tamaño máximo 200MB"
      button_msg: "🗂️ Examinar"
      tipo_archivos: ["csv", "xlsx"]
      icon: "MdUploadFile"







config_session_state:
  claves_a_conservar:
    - "selector_rango_dcto"
    - "df_insumo"
    - "text_input_crecimiento_valido"
    - "btn_confirmar_rango_estado"
    - "portje_cremto_act"
    - "btn_confirmar_%_crecimiento_widget"
    - "btn_confirmar_%_crecimiento_estado"
    - "archivo_excel"
    - "btn_confirmar_rango_widget"
    - "rango_act"
    - "text_input_crecimiento"
    - "list_materiales"



url_app_apscritp: https://script.google.com/macros/s/AKfycbxrLMi97hhKLNp6aL0a6fumxo6TvZvXX58bX1WaSSesF5aoKcfdMOUnCSHa7wGE62ApMQ/exec

textos:
  titulo_principal: "Interfaz Interactiva con Múltiples Selecciones"
  subtitulo: "Selección de Materiales y Porcentajes"
  agregar_fila: "Agregar nueva fila"
  seleccionar_materiales: "Seleccionar Materiales"
  seleccionar_meses: "Seleccionar Meses"
  construir_tabla: "Construir tabla"
  seleccion_material_placeholder: "Selecciona un material:"
  seleccion_mes_placeholder: "Selecciona un mes:"
  mensaje_exito: "¡Perfecto, los materiales suman el "
  mensaje_advertencia: "Ajusta los valores. Los materiales aún no suman el "
  mensaje_error: "Ajusta los valores. Los materiales no pueden sumar más del " 























mes_actual: Febrero
concepto: 
  Concurso regional de logros:
    primer_lugar: Concurso regional de logros {mes_actual} cumple piso 60 logros 1er lugar.
    segundo_lugar: Concurso regional de logros {mes_actual} cumple piso 60 logros 2do lugar.
    resto: Concurso regional de logros {mes_actual} cumple piso 60 logros.
    primer_lugar_especial: Concurso regional de logros {mes_actual} frente comercial
    segundo_lugar_especial: Concurso regional de logros {mes_actual} frente comercial
  Gestión inventario. :
    resto : Gestión inventario {mes_actual} 
  IGPT:
    resto : IGPT {mes_actual} 
  
