
# Configuraciones de usuario. 

cnf_concep_herr:
  concepto:
    - "Canasta del ahorro"
    - "Irresistibles"
    - "Mega ofertas"
    - "Concepto 4"
    - "Concepto 5"
    - "Concepto 6"
    - "Concepto 7"
  herramienta:
    - "Reposicion: presentaciones pequeñas. Viernes a lunes"
    - "Alacena tamaños grandes, va sabado a viernes"
    - "Alacena: presentaciones grandes, descuentos profundos"
    - "Listas complementarias"
    - "Mi descuento"
    - "Descuentos de aniversario"

df_insumo:
  dict_cols : {
    "Mes": "Mes",
    "Vigencia": "Vigencia",
    "# ofertas": "# ofertas",
    "plu": "plu",
    "producto": "producto",
    "Marca": "Marca",
    "Sub": "Sub",
    "Venta $$ Promedio Mes": "Venta $$ Promedio Mes",
    "Promedio Mes Und": "Promedio Mes Und",
    "Precio de venta": "Precio de venta",
    "Dias de la actividad" : "Dias de la actividad"
  }
  cols_select:
    - "concat_plu_producto"
    - "plu"
    - "producto"
    - "Marca"
    - "Sub"
    - "Venta $$ Promedio Mes"
    - "Promedio Mes Und"
    - "Precio de venta"


lateral_var:
  encabezado: "Menu"

  seccion_rango_descuento:
    select_box_rng:
      clave: "selector_rango_dcto"
      etiqueta : "Seleccione un rango de descuento..."
      list_rng_dctos:
      - "5% - 10%"
      - "10% - 15%"
      - "15% - 20%"
      - "20% - 25%"
      - "25% - 30%"
      - "30% - 35%"
      - "35% - 40%"
      - "40% - 45%"
      - "45% - 50%"
    btn_confirmar_rng:
      clave : btn_confirmar_rango
      etiqueta : Confirmar rango %

  seccion_crecimiento:
    text_input_crec:
      clave: "text_input_crecimiento"
      etiqueta: "Ingrese % de crecimiento:"
      valor_por_defecto: 10
      minimo: 1
      maximo: 50
    btn_confirmar_rng:
      clave : "btn_confirmar_%_crecimiento"
      etiqueta : "Confirmar % crecimiento"

  seccion_archivo:
    file_uploader_precios:
      clave: "archivo_excel_prec"
      titulo: "Cargar archivo precios"
      uploader_msg: "📤 Adjuntar archivo precios"
      limit_msg: "Tamaño máximo 200MB"
      button_msg: "🗂️ Examinar"
      tipo_archivos: ["csv", "xlsx"]
      icon: "MdUploadFile"

    file_uploader_vtas:
      clave: "archivo_excel_vtas"
      titulo: "Cargar archivo ventas"
      uploader_msg: "📤 Adjuntar archivo vtas"
      limit_msg: "Tamaño máximo 200MB"
      button_msg: "🗂️ Examinar"
      tipo_archivos: ["csv", "xlsx"]
      icon: "MdUploadFile"

    file_uploader:
      clave: "archivo_excel"
      titulo: "Cargar archivo"
      uploader_msg: "📤 Adjuntar archivo Excel"
      limit_msg: "Tamaño máximo 200MB"
      button_msg: "🗂️ Examinar"
      tipo_archivos: ["csv", "xlsx"]
      icon: "MdUploadFile"

cnf_columnas_data:
  eliminar_col: "Eliminar"
  concat_col: "concat_plu_producto"

cnf_session_keys:
  editor_df_key: "editor_df_final"
  inicializacion:
    list_materiales:
      valor_inicial: []
    registro_confirmado: 
      valor_inicial: false
    confirmar_edicion_pendiente: 
      valor_inicial: false
  
  claves_preservar:
    - "selector_rango_dcto"
    - "df_insumo"
    - "df_final"
    - "text_input_crecimiento_valido"
    - "portje_cremto_act"
    - "rango_act"
    - "list_materiales"
    - "registro_confirmado"
    - "confirmar_edicion_pendiente"
    - "archivo_excel"

  lista_materiales: "list_materiales"
  dataframe_final: "df_final"
  registro_confirmado: "registro_confirmado"
  edicion_confirmada: "edicion_confirmada"

cnf_botones:
  agregar_material:
    clave: "Agregar_mat"
    etiqueta: "Agregar material"
    usar_sidebar: true
    auto_render: true
  
  confirmar_registro:
    clave: "confirmar_registro"
    etiqueta: "✅ Confirmar registro"
    usar_sidebar: false
    auto_render: false

  confirmar_edicion:
    clave: "confirmar_edicion"
    etiqueta: "💾 Confirmar edición"
    usar_sidebar: false
    auto_render: false

  eliminar_filas:
    clave: "eliminar_filas"
    etiqueta: "🗑️ Eliminar filas seleccionadas"
    usar_sidebar: false
    auto_render: false


cnf_mensajes:
  registro_exitoso: "✅ Registro confirmado. Ahora puedes editar los datos."
  edicion_exitosa: "✅ Edición confirmada."
  eliminacion_exitosa: "✅ Filas eliminadas correctamente."
  sin_insumos: "⚠️ Aún no se ha cargado un archivo de insumos."
  editar_titulo: "✏️ Editar datos registrados"



